package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adres generated by hbm2java
 */
public class Adres  implements java.io.Serializable {


     private Integer idAdres;
     private Klient klient;
     private String wojewodztwo;
     private String powiat;
     private String kodPocztowy;
     private String miejscowosc;
     private String ulica;
     private String nrLokalu;
     private Set zamowienies = new HashSet(0);

    public Adres() {
    }

	
    public Adres(String wojewodztwo, String powiat, String kodPocztowy, String miejscowosc, String ulica, String nrLokalu) {
        this.wojewodztwo = wojewodztwo;
        this.powiat = powiat;
        this.kodPocztowy = kodPocztowy;
        this.miejscowosc = miejscowosc;
        this.ulica = ulica;
        this.nrLokalu = nrLokalu;
    }
    public Adres(Klient klient, String wojewodztwo, String powiat, String kodPocztowy, String miejscowosc, String ulica, String nrLokalu, Set zamowienies) {
       this.klient = klient;
       this.wojewodztwo = wojewodztwo;
       this.powiat = powiat;
       this.kodPocztowy = kodPocztowy;
       this.miejscowosc = miejscowosc;
       this.ulica = ulica;
       this.nrLokalu = nrLokalu;
       this.zamowienies = zamowienies;
    }
   
    public Integer getIdAdres() {
        return this.idAdres;
    }
    
    public void setIdAdres(Integer idAdres) {
        this.idAdres = idAdres;
    }
    public Klient getKlient() {
        return this.klient;
    }
    
    public void setKlient(Klient klient) {
        this.klient = klient;
    }
    public String getWojewodztwo() {
        return this.wojewodztwo;
    }
    
    public void setWojewodztwo(String wojewodztwo) {
        this.wojewodztwo = wojewodztwo;
    }
    public String getPowiat() {
        return this.powiat;
    }
    
    public void setPowiat(String powiat) {
        this.powiat = powiat;
    }
    public String getKodPocztowy() {
        return this.kodPocztowy;
    }
    
    public void setKodPocztowy(String kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }
    public String getMiejscowosc() {
        return this.miejscowosc;
    }
    
    public void setMiejscowosc(String miejscowosc) {
        this.miejscowosc = miejscowosc;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getNrLokalu() {
        return this.nrLokalu;
    }
    
    public void setNrLokalu(String nrLokalu) {
        this.nrLokalu = nrLokalu;
    }
    public Set getZamowienies() {
        return this.zamowienies;
    }
    
    public void setZamowienies(Set zamowienies) {
        this.zamowienies = zamowienies;
    }




}


