package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dostawca generated by hbm2java
 */
public class Dostawca  implements java.io.Serializable {


     private Integer idDostawca;
     private String nazwa;
     private String nip;
     private String regon;
     private float cena;
     private String czasDostawy;
     private Set zamowienieDostawcas = new HashSet(0);

    public Dostawca() {
    }

	
    public Dostawca(String nazwa, String nip, String regon, float cena, String czasDostawy) {
        this.nazwa = nazwa;
        this.nip = nip;
        this.regon = regon;
        this.cena = cena;
        this.czasDostawy = czasDostawy;
    }
    public Dostawca(String nazwa, String nip, String regon, float cena, String czasDostawy, Set zamowienieDostawcas) {
       this.nazwa = nazwa;
       this.nip = nip;
       this.regon = regon;
       this.cena = cena;
       this.czasDostawy = czasDostawy;
       this.zamowienieDostawcas = zamowienieDostawcas;
    }
   
    public Integer getIdDostawca() {
        return this.idDostawca;
    }
    
    public void setIdDostawca(Integer idDostawca) {
        this.idDostawca = idDostawca;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }
    public String getRegon() {
        return this.regon;
    }
    
    public void setRegon(String regon) {
        this.regon = regon;
    }
    public float getCena() {
        return this.cena;
    }
    
    public void setCena(float cena) {
        this.cena = cena;
    }
    public String getCzasDostawy() {
        return this.czasDostawy;
    }
    
    public void setCzasDostawy(String czasDostawy) {
        this.czasDostawy = czasDostawy;
    }
    public Set getZamowienieDostawcas() {
        return this.zamowienieDostawcas;
    }
    
    public void setZamowienieDostawcas(Set zamowienieDostawcas) {
        this.zamowienieDostawcas = zamowienieDostawcas;
    }




}


