package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Faktura generated by hbm2java
 */
public class Faktura  implements java.io.Serializable {


     private Integer idFaktura;
     private Zamowienie zamowienie;
     private float wartoscNetto;
     private float wartoscBrutto;
     private float wartoscVat;
     private Date terminZaplaty;
     private String formaPlatnosci;
     private Date dataSprzedazy;
     private Set pozycjaFakturies = new HashSet(0);

    public Faktura() {
    }

	
    public Faktura(float wartoscNetto, float wartoscBrutto, float wartoscVat, Date terminZaplaty, String formaPlatnosci, Date dataSprzedazy) {
        this.wartoscNetto = wartoscNetto;
        this.wartoscBrutto = wartoscBrutto;
        this.wartoscVat = wartoscVat;
        this.terminZaplaty = terminZaplaty;
        this.formaPlatnosci = formaPlatnosci;
        this.dataSprzedazy = dataSprzedazy;
    }
    public Faktura(Zamowienie zamowienie, float wartoscNetto, float wartoscBrutto, float wartoscVat, Date terminZaplaty, String formaPlatnosci, Date dataSprzedazy, Set pozycjaFakturies) {
       this.zamowienie = zamowienie;
       this.wartoscNetto = wartoscNetto;
       this.wartoscBrutto = wartoscBrutto;
       this.wartoscVat = wartoscVat;
       this.terminZaplaty = terminZaplaty;
       this.formaPlatnosci = formaPlatnosci;
       this.dataSprzedazy = dataSprzedazy;
       this.pozycjaFakturies = pozycjaFakturies;
    }
   
    public Integer getIdFaktura() {
        return this.idFaktura;
    }
    
    public void setIdFaktura(Integer idFaktura) {
        this.idFaktura = idFaktura;
    }
    public Zamowienie getZamowienie() {
        return this.zamowienie;
    }
    
    public void setZamowienie(Zamowienie zamowienie) {
        this.zamowienie = zamowienie;
    }
    public float getWartoscNetto() {
        return this.wartoscNetto;
    }
    
    public void setWartoscNetto(float wartoscNetto) {
        this.wartoscNetto = wartoscNetto;
    }
    public float getWartoscBrutto() {
        return this.wartoscBrutto;
    }
    
    public void setWartoscBrutto(float wartoscBrutto) {
        this.wartoscBrutto = wartoscBrutto;
    }
    public float getWartoscVat() {
        return this.wartoscVat;
    }
    
    public void setWartoscVat(float wartoscVat) {
        this.wartoscVat = wartoscVat;
    }
    public Date getTerminZaplaty() {
        return this.terminZaplaty;
    }
    
    public void setTerminZaplaty(Date terminZaplaty) {
        this.terminZaplaty = terminZaplaty;
    }
    public String getFormaPlatnosci() {
        return this.formaPlatnosci;
    }
    
    public void setFormaPlatnosci(String formaPlatnosci) {
        this.formaPlatnosci = formaPlatnosci;
    }
    public Date getDataSprzedazy() {
        return this.dataSprzedazy;
    }
    
    public void setDataSprzedazy(Date dataSprzedazy) {
        this.dataSprzedazy = dataSprzedazy;
    }
    public Set getPozycjaFakturies() {
        return this.pozycjaFakturies;
    }
    
    public void setPozycjaFakturies(Set pozycjaFakturies) {
        this.pozycjaFakturies = pozycjaFakturies;
    }




}


