package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kategoria generated by hbm2java
 */
public class Kategoria  implements java.io.Serializable {


     private Integer idKategoria;
     private String nazwaKategorii;
     private Set kategoriaProducents = new HashSet(0);

    public Kategoria() {
    }

    public Kategoria(String nazwaKategorii, Set kategoriaProducents) {
       this.nazwaKategorii = nazwaKategorii;
       this.kategoriaProducents = kategoriaProducents;
    }
   
    public Integer getIdKategoria() {
        return this.idKategoria;
    }
    
    public void setIdKategoria(Integer idKategoria) {
        this.idKategoria = idKategoria;
    }
    public String getNazwaKategorii() {
        return this.nazwaKategorii;
    }
    
    public void setNazwaKategorii(String nazwaKategorii) {
        this.nazwaKategorii = nazwaKategorii;
    }
    public Set getKategoriaProducents() {
        return this.kategoriaProducents;
    }
    
    public void setKategoriaProducents(Set kategoriaProducents) {
        this.kategoriaProducents = kategoriaProducents;
    }




}


