package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * KategoriaProducent generated by hbm2java
 */
public class KategoriaProducent  implements java.io.Serializable {


     private Integer idKatProd;
     private Kategoria kategoria;
     private Producent producent;
     private Set produkts = new HashSet(0);

    public KategoriaProducent() {
    }

    public KategoriaProducent(Kategoria kategoria, Producent producent, Set produkts) {
       this.kategoria = kategoria;
       this.producent = producent;
       this.produkts = produkts;
    }
   
    public Integer getIdKatProd() {
        return this.idKatProd;
    }
    
    public void setIdKatProd(Integer idKatProd) {
        this.idKatProd = idKatProd;
    }
    public Kategoria getKategoria() {
        return this.kategoria;
    }
    
    public void setKategoria(Kategoria kategoria) {
        this.kategoria = kategoria;
    }
    public Producent getProducent() {
        return this.producent;
    }
    
    public void setProducent(Producent producent) {
        this.producent = producent;
    }
    public Set getProdukts() {
        return this.produkts;
    }
    
    public void setProdukts(Set produkts) {
        this.produkts = produkts;
    }




}


