package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Klient generated by hbm2java
 */
public class Klient implements java.io.Serializable {

    private Integer idKlient;
    private String imie;
    private String nazwisko;
    private String login;
    private String haslo;
    private String nazwaFirmy;
    private String EMail;
    private String nrTelefonu;
    private Set adreses = new HashSet(0);
    private Set zamowienies = new HashSet(0);

    public Klient() {
    }

    public Klient(String login, String haslo, String EMail, String nrTelefonu) {
        this.login = login;
        this.haslo = haslo;
        this.EMail = EMail;
        this.nrTelefonu = nrTelefonu;
    }

    public Klient(String imie, String nazwisko, String login, String haslo, String nazwaFirmy, String EMail, String nrTelefonu, Set adreses, Set zamowienies) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.login = login;
        this.haslo = haslo;
        this.nazwaFirmy = nazwaFirmy;
        this.EMail = EMail;
        this.nrTelefonu = nrTelefonu;
        this.adreses = adreses;
        this.zamowienies = zamowienies;
    }

    public Integer getIdKlient() {
        return this.idKlient;
    }

    public void setIdKlient(Integer idKlient) {
        this.idKlient = idKlient;
    }

    public String getImie() {
        return this.imie;
    }

    public void setImie(String imie) {
        this.imie = imie;
    }

    public String getNazwisko() {
        return this.nazwisko;
    }

    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getHaslo() {
        return this.haslo;
    }

    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }

    public String getNazwaFirmy() {
        return this.nazwaFirmy;
    }

    public void setNazwaFirmy(String nazwaFirmy) {
        this.nazwaFirmy = nazwaFirmy;
    }

    public String getEMail() {
        return this.EMail;
    }

    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    public String getNrTelefonu() {
        return this.nrTelefonu;
    }

    public void setNrTelefonu(String nrTelefonu) {
        this.nrTelefonu = nrTelefonu;
    }

    public Set getAdreses() {
        return this.adreses;
    }

    public void setAdreses(Set adreses) {
        this.adreses = adreses;
    }

    public Set getZamowienies() {
        return this.zamowienies;
    }

    public void setZamowienies(Set zamowienies) {
        this.zamowienies = zamowienies;
    }

    

}
