package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Opinia generated by hbm2java
 */
public class Opinia  implements java.io.Serializable {


     private Integer idOpinia;
     private Produkt produkt;
     private String tresc;
     private String nazwaUzytkownika;
     private Date dataWystawienia;
     private byte ocena;

    public Opinia() {
    }

	
    public Opinia(String tresc, String nazwaUzytkownika, Date dataWystawienia, byte ocena) {
        this.tresc = tresc;
        this.nazwaUzytkownika = nazwaUzytkownika;
        this.dataWystawienia = dataWystawienia;
        this.ocena = ocena;
    }
    public Opinia(Produkt produkt, String tresc, String nazwaUzytkownika, Date dataWystawienia, byte ocena) {
       this.produkt = produkt;
       this.tresc = tresc;
       this.nazwaUzytkownika = nazwaUzytkownika;
       this.dataWystawienia = dataWystawienia;
       this.ocena = ocena;
    }
   
    public Integer getIdOpinia() {
        return this.idOpinia;
    }
    
    public void setIdOpinia(Integer idOpinia) {
        this.idOpinia = idOpinia;
    }
    public Produkt getProdukt() {
        return this.produkt;
    }
    
    public void setProdukt(Produkt produkt) {
        this.produkt = produkt;
    }
    public String getTresc() {
        return this.tresc;
    }
    
    public void setTresc(String tresc) {
        this.tresc = tresc;
    }
    public String getNazwaUzytkownika() {
        return this.nazwaUzytkownika;
    }
    
    public void setNazwaUzytkownika(String nazwaUzytkownika) {
        this.nazwaUzytkownika = nazwaUzytkownika;
    }
    public Date getDataWystawienia() {
        return this.dataWystawienia;
    }
    
    public void setDataWystawienia(Date dataWystawienia) {
        this.dataWystawienia = dataWystawienia;
    }
    public byte getOcena() {
        return this.ocena;
    }
    
    public void setOcena(byte ocena) {
        this.ocena = ocena;
    }




}


