package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1



/**
 * PozycjaFaktury generated by hbm2java
 */
public class PozycjaFaktury  implements java.io.Serializable {


     private Integer idPozycjaFaktury;
     private Faktura faktura;
     private Produkt produkt;
     private float cenaNettoSprzedazy;
     private float cenaBruttoSprzedazy;
     private float procentVatSprzedazy;
     private int iloscSztuk;

    public PozycjaFaktury() {
    }

	
    public PozycjaFaktury(float cenaNettoSprzedazy, float cenaBruttoSprzedazy, float procentVatSprzedazy, int iloscSztuk) {
        this.cenaNettoSprzedazy = cenaNettoSprzedazy;
        this.cenaBruttoSprzedazy = cenaBruttoSprzedazy;
        this.procentVatSprzedazy = procentVatSprzedazy;
        this.iloscSztuk = iloscSztuk;
    }
    public PozycjaFaktury(Faktura faktura, Produkt produkt, float cenaNettoSprzedazy, float cenaBruttoSprzedazy, float procentVatSprzedazy, int iloscSztuk) {
       this.faktura = faktura;
       this.produkt = produkt;
       this.cenaNettoSprzedazy = cenaNettoSprzedazy;
       this.cenaBruttoSprzedazy = cenaBruttoSprzedazy;
       this.procentVatSprzedazy = procentVatSprzedazy;
       this.iloscSztuk = iloscSztuk;
    }
   
    public Integer getIdPozycjaFaktury() {
        return this.idPozycjaFaktury;
    }
    
    public void setIdPozycjaFaktury(Integer idPozycjaFaktury) {
        this.idPozycjaFaktury = idPozycjaFaktury;
    }
    public Faktura getFaktura() {
        return this.faktura;
    }
    
    public void setFaktura(Faktura faktura) {
        this.faktura = faktura;
    }
    public Produkt getProdukt() {
        return this.produkt;
    }
    
    public void setProdukt(Produkt produkt) {
        this.produkt = produkt;
    }
    public float getCenaNettoSprzedazy() {
        return this.cenaNettoSprzedazy;
    }
    
    public void setCenaNettoSprzedazy(float cenaNettoSprzedazy) {
        this.cenaNettoSprzedazy = cenaNettoSprzedazy;
    }
    public float getCenaBruttoSprzedazy() {
        return this.cenaBruttoSprzedazy;
    }
    
    public void setCenaBruttoSprzedazy(float cenaBruttoSprzedazy) {
        this.cenaBruttoSprzedazy = cenaBruttoSprzedazy;
    }
    public float getProcentVatSprzedazy() {
        return this.procentVatSprzedazy;
    }
    
    public void setProcentVatSprzedazy(float procentVatSprzedazy) {
        this.procentVatSprzedazy = procentVatSprzedazy;
    }
    public int getIloscSztuk() {
        return this.iloscSztuk;
    }
    
    public void setIloscSztuk(int iloscSztuk) {
        this.iloscSztuk = iloscSztuk;
    }




}


