package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produkt generated by hbm2java
 */
public class Produkt  implements java.io.Serializable {


     private Integer idProdukt;
     private KategoriaProducent kategoriaProducent;
     private String nazwa;
     private String opis;
     private float cenaNettoAktualna;
     private float cenaBruttoAktualna;
     private float procentVat;
     private int ilosc;
     private Set pozycjaFakturies = new HashSet(0);
     private Set zamowienieProdukts = new HashSet(0);
     private Set opinias = new HashSet(0);
     private Set zdjecies = new HashSet(0);

    public Produkt() {
    }

	
    public Produkt(String nazwa, String opis, float cenaNettoAktualna, float cenaBruttoAktualna, float procentVat, int ilosc) {
        this.nazwa = nazwa;
        this.opis = opis;
        this.cenaNettoAktualna = cenaNettoAktualna;
        this.cenaBruttoAktualna = cenaBruttoAktualna;
        this.procentVat = procentVat;
        this.ilosc = ilosc;
    }
    public Produkt(KategoriaProducent kategoriaProducent, String nazwa, String opis, float cenaNettoAktualna, float cenaBruttoAktualna, float procentVat, int ilosc, Set pozycjaFakturies, Set zamowienieProdukts, Set opinias, Set zdjecies) {
       this.kategoriaProducent = kategoriaProducent;
       this.nazwa = nazwa;
       this.opis = opis;
       this.cenaNettoAktualna = cenaNettoAktualna;
       this.cenaBruttoAktualna = cenaBruttoAktualna;
       this.procentVat = procentVat;
       this.ilosc = ilosc;
       this.pozycjaFakturies = pozycjaFakturies;
       this.zamowienieProdukts = zamowienieProdukts;
       this.opinias = opinias;
       this.zdjecies = zdjecies;
    }
   
    public Integer getIdProdukt() {
        return this.idProdukt;
    }
    
    public void setIdProdukt(Integer idProdukt) {
        this.idProdukt = idProdukt;
    }
    public KategoriaProducent getKategoriaProducent() {
        return this.kategoriaProducent;
    }
    
    public void setKategoriaProducent(KategoriaProducent kategoriaProducent) {
        this.kategoriaProducent = kategoriaProducent;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public float getCenaNettoAktualna() {
        return this.cenaNettoAktualna;
    }
    
    public void setCenaNettoAktualna(float cenaNettoAktualna) {
        this.cenaNettoAktualna = cenaNettoAktualna;
    }
    public float getCenaBruttoAktualna() {
        return this.cenaBruttoAktualna;
    }
    
    public void setCenaBruttoAktualna(float cenaBruttoAktualna) {
        this.cenaBruttoAktualna = cenaBruttoAktualna;
    }
    public float getProcentVat() {
        return this.procentVat;
    }
    
    public void setProcentVat(float procentVat) {
        this.procentVat = procentVat;
    }
    public int getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(int ilosc) {
        this.ilosc = ilosc;
    }
    public Set getPozycjaFakturies() {
        return this.pozycjaFakturies;
    }
    
    public void setPozycjaFakturies(Set pozycjaFakturies) {
        this.pozycjaFakturies = pozycjaFakturies;
    }
    public Set getZamowienieProdukts() {
        return this.zamowienieProdukts;
    }
    
    public void setZamowienieProdukts(Set zamowienieProdukts) {
        this.zamowienieProdukts = zamowienieProdukts;
    }
    public Set getOpinias() {
        return this.opinias;
    }
    
    public void setOpinias(Set opinias) {
        this.opinias = opinias;
    }
    public Set getZdjecies() {
        return this.zdjecies;
    }
    
    public void setZdjecies(Set zdjecies) {
        this.zdjecies = zdjecies;
    }




}


