package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1



/**
 * ZamowienieProdukt generated by hbm2java
 */
public class ZamowienieProdukt  implements java.io.Serializable {


     private Integer idZamProd;
     private Produkt produkt;
     private Zamowienie zamowienie;
     private int iloscProduktu;

    public ZamowienieProdukt() {
    }

	
    public ZamowienieProdukt(int iloscProduktu) {
        this.iloscProduktu = iloscProduktu;
    }
    public ZamowienieProdukt(Produkt produkt, Zamowienie zamowienie, int iloscProduktu) {
       this.produkt = produkt;
       this.zamowienie = zamowienie;
       this.iloscProduktu = iloscProduktu;
    }
   
    public Integer getIdZamProd() {
        return this.idZamProd;
    }
    
    public void setIdZamProd(Integer idZamProd) {
        this.idZamProd = idZamProd;
    }
    public Produkt getProdukt() {
        return this.produkt;
    }
    
    public void setProdukt(Produkt produkt) {
        this.produkt = produkt;
    }
    public Zamowienie getZamowienie() {
        return this.zamowienie;
    }
    
    public void setZamowienie(Zamowienie zamowienie) {
        this.zamowienie = zamowienie;
    }
    public int getIloscProduktu() {
        return this.iloscProduktu;
    }
    
    public void setIloscProduktu(int iloscProduktu) {
        this.iloscProduktu = iloscProduktu;
    }




}


