package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1



/**
 * ZamowienieDostawca generated by hbm2java
 */
public class ZamowienieDostawca  implements java.io.Serializable {


     private Integer idZamDost;
     private Dostawca dostawca;
     private Zamowienie zamowienie;

    public ZamowienieDostawca() {
    }

    public ZamowienieDostawca(Dostawca dostawca, Zamowienie zamowienie) {
       this.dostawca = dostawca;
       this.zamowienie = zamowienie;
    }
   
    public Integer getIdZamDost() {
        return this.idZamDost;
    }
    
    public void setIdZamDost(Integer idZamDost) {
        this.idZamDost = idZamDost;
    }
    public Dostawca getDostawca() {
        return this.dostawca;
    }
    
    public void setDostawca(Dostawca dostawca) {
        this.dostawca = dostawca;
    }
    public Zamowienie getZamowienie() {
        return this.zamowienie;
    }
    
    public void setZamowienie(Zamowienie zamowienie) {
        this.zamowienie = zamowienie;
    }




}


