package model;
// Generated 2016-12-05 21:50:16 by Hibernate Tools 4.3.1



/**
 * Zdjecie generated by hbm2java
 */
public class Zdjecie  implements java.io.Serializable {


     private Integer idZdjecie;
     private Produkt produkt;
     private String nazwaPliku;

    public Zdjecie() {
    }

	
    public Zdjecie(String nazwaPliku) {
        this.nazwaPliku = nazwaPliku;
    }
    public Zdjecie(Produkt produkt, String nazwaPliku) {
       this.produkt = produkt;
       this.nazwaPliku = nazwaPliku;
    }
   
    public Integer getIdZdjecie() {
        return this.idZdjecie;
    }
    
    public void setIdZdjecie(Integer idZdjecie) {
        this.idZdjecie = idZdjecie;
    }
    public Produkt getProdukt() {
        return this.produkt;
    }
    
    public void setProdukt(Produkt produkt) {
        this.produkt = produkt;
    }
    public String getNazwaPliku() {
        return this.nazwaPliku;
    }
    
    public void setNazwaPliku(String nazwaPliku) {
        this.nazwaPliku = nazwaPliku;
    }




}


